function fig = plot_ik_chain(chain,ik)
%
% Plot IK status
%

fig = plot_chain(chain,'fig_pos',[0.0,0.5,0.3,0.45],'view_info',[88,4],'axis_info','',...
    'PLOT_MESH',1,'mfa',0.4,'PLOT_LINK',1,'PLOT_ROTATE_AXIS',1,'PLOT_JOINT_AXIS',0,...
    'PLOT_JOINT_SPHERE',0,'PRINT_JOINT_NAME',0,'view_info',[60,14],...
    'title_str',sprintf('[%d][%.3f]',ik.tick,ik.err));
plot_T(pr2t([0,0,0]',rpy2r([0,0,0]')),'subfig_idx',1,'PLOT_SPHERE',0,'alw',4); % world coord
for i_idx = 1:ik.n_target
    plot_T(pr2t(ik.targets(i_idx).p,ik.targets(i_idx).R),'subfig_idx',2*i_idx,...
        'PLOT_SPHERE',1,'sr',0.02,'sfc','r','sfa',0.8,'alen',0.1,'alw',4); % IK target
    plot_T(pr2t(chain.joint(ik.targets(i_idx).joint_idx).p,...
        chain.joint(ik.targets(i_idx).joint_idx).R),'subfig_idx',1+2*i_idx,...
        'PLOT_SPHERE',1,'sr',0.02,'sfa',0.8,'alen',0.1,'alw',4); % Current joint
end
drawnow limitrate;
