function print_bocd(bocd)

fprintf(['iter:[%d/%d] bocd mode:[%s] bo_step:[%d/%d] cd_step:[%d/%d] '...
    'n:[%d] curr_cost:[%.3f] cost_best:[%.3f]. \n'],...
    bocd.iter,bocd.max_iter,bocd.mode,...
    bocd.bo_step,bocd.max_bo_step,bocd.cd_step,bocd.max_cd_step,...
    bocd.n,bocd.cost_added,bocd.cost_best);
